### ISSUE TITLE
Failed to apply Install

### ISSUE THREAD

**Issue by romainpoirier** [lukeyouell/craft-emailvalidator#13]
I get this error when I try to install the plugin from the CP after its downloading:

```
[-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.510s). Output:
    > create table {{%ev_providers}} ... done (time: 0.005s)
Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "ev_providers"
LINE 1: SELECT "ev_providers"."id", "ev_providers"."type", "ev_provi...
               ^
The SQL being executed was: SELECT "ev_providers"."id", "ev_providers"."type", "ev_providers"."domain"
FROM "craft_ev_providers"
WHERE ("domain"='1033edge.com') AND ("type"='free')
ORDER BY "dateCreated"
LIMIT 1
```

I removed the plugin (using Composer), try to reinstall it (from Composer + from the CP), also tried an installation from the previous release, but I still get this error.

**Comment by lukeyouell** [comment]
@romainpoirier do you by any chance have a table prefix?

**Comment by romainpoirier** [comment]
`DB_TABLE_PREFIX="craft_"` is set like this in my .env file.

**Comment by lukeyouell** [comment]
That might be why, which is totally my fault. I'll look into it!

**Comment by lukeyouell** [comment]
Fixed and released! Sorry about that!

**Comment by romainpoirier** [comment]
Perfect, now the installation works! Thank you for fixing it so quickly.
