### ISSUE TITLE
Support for Guest Entries?

### ISSUE THREAD

**Issue by mikestecker** [lukeyouell/craft-emailvalidator#16]
Is there a way I could use this with the [Guest Entries](https://github.com/craftcms/guest-entries) plugin? I have a simple `email` field that I'd love to tie this in with, similar to the contact form.

Also, if there was a way to hit this via AJAX on the front end, that would be really cool, this way the user doesn't have to fully submit the form.

**Comment by lukeyouell** [comment]
Hey Mike! You could create a simple module that uses the Guest Entries [before save event](https://github.com/craftcms/guest-entries/blob/v2/src/controllers/SaveController.php#L44) to call the validation service like in the docs: https://github.com/lukeyouell/craft-emailvalidator#pluginsmodules

**Comment by mikestecker** [comment]
@lukeyouell Thanks for the reply! Cool thanks for pointing me in that direction. I'll work on going in that direction. I was hoping to do some sort of AJAX lookup as the user types. Maybe I can figure out how to make a new route just to validate the email.
